### ISSUE TITLE
Adds Vary: Cookie to requests

### ISSUE THREAD

**Issue by thenewguy** [coderedcorp/wagtail-cache#29]
I am seeing `Vary: Cookie` added to requests when `WAGTAIL_CACHE = True` for responses that do not contain `Vary: Cookie` when `WAGTAIL_CACHE = False`

**Comment by thenewguy** [comment]
Adding `Vary: Cookie` prevents the reverse proxy (or CDN - like Cloudfront) from serving the cached response to another session. Introducing `Vary: Cookie` when it isn't required means that anonymous content cannot be reused. This is important for caching anonymous page views, wagtail's dynamic image serve view, and other assets served by Django that are not user specific.

**Comment by vsalvino** [comment]
Going back to the original issue, the Django Session middleware is the thing adding Vary: Cookie to ALL responses. In order to skirt that, we have added the new WAGTAIL_CACHE_IGNORE_COOKIES setting which essentially strips all non-Django cookies from the request, and removes the Vary: Cookie header if there is not a Django session or CSRF token.

**Comment by thenewguy** [comment]
I just saw this. I've been out of town. If you would merge my tests and the updated checks I'm happy to rework it.

**Comment by vsalvino** [comment]
Closing this as the Vary header handling has been previously re-worked. Feel free to re-open if you have any new information.
