### ISSUE TITLE
Use with password-protected pages

### ISSUE THREAD

**Issue by philgyford** [coderedcorp/wagtail-cache#9]
I'm using wagtail-cache on a site where we often publish password-protected pages. I'm finding that these often get stuck - either the "Password required" form keeps returning, despite the correct password being used, or I get CSRF errors.

The `X-Wagtail-Cache` header indicates a 'hit' when these pages are displayed, so I'm *guessing* this problem is due to caching. Has anyone come across this and/or is there a way to prevent wagtail-cache caching these pages?

**Comment by vsalvino** [comment]
Yes, you are absolutely correct. There is the exact same issue on CodeRed CMS https://github.com/coderedcorp/coderedcms/issues/97 

Since wagtail-cache does not have access to the `page` object at all, my solution is to check the `response` object that is returned after the view is run, but before the response is served/cached. This check will not cache anything with a respective `Cache-Control` header that indicates no-cache or private. A mixin utility will then be provided that you can add to your models to ensure they set the Cache-Control header properly.

**Comment by vsalvino** [comment]
Hey @philgyford  - I have a fix up in the `mixin` branch. See pull request #10 . Would appreciate it if you could take a look at the code and/or try it out on your project to see if it works better.

New documentation was added in the branch to show how to use. I would also appreciate any doc suggestions.

**Comment by philgyford** [comment]
I've only been able to try it out on my local copy of the site, which for some reason doesn't suffer from the same issue... but I can see that the `Cache-Control: private` header has been set now, when viewing the password page.

I'm not sure how to make my staging site use this particular commit of wagtail-cache - it's being a bit stubborn!

Anyway, looks good so far. My only thought is that, given any Wagtail Page could potentially be password protected, doesn't that mean you should *always* add the `WagtailCacheMixin` to every Page? Otherwise that feature of Wagtail won't work correctly.

**Comment by vsalvino** [comment]
I believe you could install as so:
```
pip install https://github.com/coderedcorp/wagtail-cache/archive/mixin.zip
```
And yes, if you did not use `WagtailCacheMixin` it would by default cache the password protected pages, unless you manually added `response['Cache-Control'] = 'private'` at some point. The mixin is not required for wagtail-cache to work, but it is required for it to work ideally.

**Comment by philgyford** [comment]
Yes, I've installed it OK locally with pipenv, but Heroku doesn't seem to have noticed I've changed the definition of which version to install.

I don't know anything about how wagtail-cache works, so maybe this isn't possible, but could it send `Cache-Control: private` by default when a page is protected by password or login? Without using the mixin? That would seem the most logical default to me, I think. And then only use the mixin if you want to change this default.

**Comment by vsalvino** [comment]
Unfortunately wagtail-cache (since it is a decorator) has no access to the `page` model, only the request and the response. The problem is further compounded because wagtail uses the exact same URL, but changes the content of the page (to include either a password form or the content) depending on a specific session variable. So we literally have no way of knowing whether the page is restricted or public. The mixin gives us access to the page model so we can add `cache-control: private` to the response when a page has view restrictions.

I think the ideal solution would be if wagtail itself set the cache-control header. Then we would not need the mixin. Logically, upstream page caches would also suffer from this same problem if they tried to cache a password-required page, so I'm surprised it has not come up before.

**Comment by philgyford** [comment]
Yes, I was surprised too. We can't be the only people who have used Wagtail with both password protection and caching before...
